-- snowflake/setup/02_raw_layer.sql
-- ============================================================
-- RAW LAYER: Exact copies of incoming data. NEVER modified.
-- This is your source of truth. If CLEAN data has a bug,
-- you re-derive from RAW. RAW is immutable after load.
-- ============================================================

USE DATABASE FLIGHT_DB;
USE SCHEMA RAW;
USE WAREHOUSE FLIGHT_WH;

-- ─────────────────────────────────────────────────────────────
-- TABLE: FLIGHTS_STAGING
-- Temporary landing zone: Airflow writes here from PostgreSQL.
-- Think of it as Snowflake's inbox before processing.
-- We use VARIANT for raw_json to store the full original payload.
-- VARIANT = Snowflake's semi-structured type (JSON/XML/Avro).
-- You can query it like: raw_json:altitude::INTEGER
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FLIGHT_DB.RAW.FLIGHTS_STAGING (
    -- Surrogate key: auto-incrementing integer generated by Snowflake
    -- AUTOINCREMENT means you never insert this — Snowflake fills it
    staging_id              BIGINT          AUTOINCREMENT PRIMARY KEY,

    -- Business key: the unique event ID from our producer
    event_id                VARCHAR(100)    NOT NULL,

    -- Core flight fields
    flight_id               VARCHAR(20),
    airline                 VARCHAR(100),
    airline_iata            VARCHAR(5),
    flight_number           VARCHAR(10),
    source_airport          VARCHAR(10),
    dest_airport            VARCHAR(10),
    source_city             VARCHAR(100),
    dest_city               VARCHAR(100),

    -- Position fields: stored as FLOAT for numeric operations
    latitude                FLOAT,
    longitude               FLOAT,
    altitude                INTEGER,
    speed                   FLOAT,
    heading                 FLOAT,

    -- Status and timing
    status                  VARCHAR(30),
    departure_time          TIMESTAMP_TZ,   -- TZ = timezone-aware timestamp
    arrival_time            TIMESTAMP_TZ,
    delay_minutes           INTEGER,
    aircraft_type           VARCHAR(20),
    event_timestamp         TIMESTAMP_TZ,
    source                  VARCHAR(50),    -- 'simulator' or 'aviationstack_api'

    -- Full JSON payload: stored for debugging and re-derivation
    -- VARIANT stores ANY JSON without a schema constraint
    raw_json                VARIANT,

    -- Pipeline metadata
    loaded_at               TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP(),
    processed_by_airflow    BOOLEAN         DEFAULT FALSE,

    -- Snowflake metadata columns (automatically populated)
    -- METADATA$FILENAME: which file this row came from (useful for Snowpipe)
    -- We'll use a regular column instead
    ingestion_batch_id      VARCHAR(100)    -- Airflow run_id for traceability
)
-- Cluster by loaded_at so time-range queries are fast
-- Snowflake re-orders micro-partitions so adjacent dates are together
CLUSTER BY (DATE(loaded_at))
COMMENT = 'Staging table: temporary landing zone for raw flight events from Kafka/Postgres';


-- ─────────────────────────────────────────────────────────────
-- TABLE: FLIGHTS_RAW
-- The permanent raw layer. Every record ever ingested lives here.
-- Never DELETE from this table. Never UPDATE business columns.
-- Only Airflow pipeline control columns (is_transformed) are updated.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FLIGHT_DB.RAW.FLIGHTS_RAW (
    -- Surrogate key
    raw_id                  BIGINT          AUTOINCREMENT PRIMARY KEY,

    -- Business key (unique per event — enforced in application, not DB constraint)
    -- We avoid UNIQUE constraints in Snowflake because they're not enforced
    -- (Snowflake trusts you to handle uniqueness in your pipeline)
    event_id                VARCHAR(100)    NOT NULL,

    -- Core dimensions
    flight_id               VARCHAR(20),
    airline                 VARCHAR(100),
    airline_iata            VARCHAR(5),
    flight_number           VARCHAR(10),

    -- Geography
    source_airport          VARCHAR(10),
    dest_airport            VARCHAR(10),
    source_city             VARCHAR(100),
    dest_city               VARCHAR(100),

    -- Position snapshot (at event_timestamp)
    latitude                FLOAT,
    longitude               FLOAT,
    altitude                INTEGER,
    speed                   FLOAT,
    heading                 FLOAT,

    -- Flight state
    status                  VARCHAR(30),
    departure_time          TIMESTAMP_TZ,
    arrival_time            TIMESTAMP_TZ,
    delay_minutes           INTEGER         DEFAULT 0,
    aircraft_type           VARCHAR(20),

    -- Event timing
    event_timestamp         TIMESTAMP_TZ,   -- When the flight was at this position
    source                  VARCHAR(50),

    -- Full original payload preserved
    raw_json                VARIANT,

    -- Pipeline control columns
    loaded_at               TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP(),
    is_transformed          BOOLEAN         DEFAULT FALSE,
    transformed_at          TIMESTAMP_TZ,
    ingestion_batch_id      VARCHAR(100)
)
CLUSTER BY (DATE(event_timestamp))
DATA_RETENTION_TIME_IN_DAYS = 7    -- Time Travel: query this table as of 7 days ago
COMMENT = 'Permanent raw layer: immutable flight event records. Source of truth.';


-- ─────────────────────────────────────────────────────────────
-- INTERNAL STAGE: upload files here before COPY INTO
-- An Internal Stage is storage inside Snowflake's own cloud account.
-- Use External Stage (S3 bucket) in production for large volumes.
-- ─────────────────────────────────────────────────────────────
CREATE STAGE IF NOT EXISTS FLIGHT_DB.RAW.FLIGHTS_STAGE
    FILE_FORMAT = (
        TYPE = 'JSON'
        STRIP_OUTER_ARRAY = TRUE    -- Input file is an array of JSON objects
        IGNORE_UTF8_ERRORS = TRUE   -- Don't crash on weird characters
    )
    COMMENT = 'Internal stage for bulk loading flight JSON files';


-- ─────────────────────────────────────────────────────────────
-- FILE FORMAT: reusable JSON parsing config
-- Define once, reference by name in COPY INTO statements
-- ─────────────────────────────────────────────────────────────
CREATE FILE FORMAT IF NOT EXISTS FLIGHT_DB.RAW.JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE
    IGNORE_UTF8_ERRORS = TRUE
    DATE_FORMAT = AUTO
    TIMESTAMP_FORMAT = AUTO
COMMENT = 'Standard JSON file format for flight data ingestion';


-- ─────────────────────────────────────────────────────────────
-- VERIFY
-- ─────────────────────────────────────────────────────────────
SHOW TABLES IN SCHEMA FLIGHT_DB.RAW;
SHOW STAGES IN SCHEMA FLIGHT_DB.RAW;